global:
  scrape_interval: 5s

scrape_configs:
  # Prometheus scrapes the redis_exporter, NOT the clone directly.
  - job_name: prometheus

    static_configs:
      - targets: ['localhost:9090']


  - job_name: redis-clone
    static_configs:
      - targets: ['localhost:9121']
